### ISSUE TITLE
Rust question - Method implementation for multiple structs

### ISSUE THREAD

**Issue by fusion2222** [rust-bratislava/tunnetler#11]
In order to understand Rust syntax I have few questions:

In Rust we can make this:
```
struct Joe {
    x: f32,
    y: f32,
}

impl Joe {
    fn get_x(&self) -> &f32 { &self.x }
}
```
Lets say, we want to have `get_x` method exclusively for Joe struct. Why it cant be declared directly in `struct Joe`? Something like:

```
struct Joe {
    x: f32,
    y: f32,
    fn get_x(&self) -> &f32 { &self.x },
}

```
Also, is there possibility to make single-code implementation for multiple structs? Something like below. I would find it much more cleaner and easier. Perhaps there is some logic behind I dont quite understand with my `high-level` language background: 

```
struct Joe {
    x: f32,
    y: f32,
    fn get_x(&self) -> &f32 { &self.x },
}

struct Paul {
    x: f32,
    y: f32,
}

impl Joe && Paul {
    fn get_x(&self) -> &f32 { &self.x }
}
```

Moreover, it is a correct way in Rust to refer such implemented functions as "struct methods"?

**Comment by Kixunil** [comment]
> Why it cant be declared directly in `struct Joe`?

I don't know why it was chosen to be that way. I guess the syntax was probably chosen because of consistency with `impl Trait` and maybe also because of generic impls (If you have `struct Foo<T>` you can implement different methods for `Foo<u32>` and `Foo<String>`.) Another reason might be Rust philosophy of decoupling data from behavior. (Sounds like anti-OOP, because OOP associates data with behavior, but it's not exactly the same thing. Rust is more interface-oriented than traditional OOP.)

> Also, is there possibility to make single-code implementation for multiple structs?

If you have many (more than two) similar structs, I'd suggest using macros. In some cases it's appropriate to make those fields public. There's also an RFC "Delegation of implementation", which might get accepted soon-ish.

> Moreover, it is a correct way in Rust to refer such implemented functions as "struct methods"?

Yes, every function inside `impl` block is called method.

**Comment by fusion2222** [comment]
cool, thanks for explanation. I will create wiki page for this, so others with same questions will be able to dig for information.
